//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoTablesDataBindingInJqueryDataTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<double> Grade { get; set; }
        public Nullable<int> Fee { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> Status { get; set; }
        public string FOGName { get; set; }
    
        public virtual CourseTable CourseTable { get; set; }
    }
}
